name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Java17:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: sbt compile
        
      - name: Check Style
        run: sbt check   
        
      - name: Test
        run: sbt test  