name: Build

on:
  push:
    branches:
      - master
    tags: [ "*" ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'sbt'
      - name: Build
        run: sbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'sbt'
      - name: Check Style
        run: sbt check
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'sbt'
      - name: Test
        run: sbt test
  
  verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'sbt'
      - name: Check Binary Compatibility
        run: sbt runPluginVerifier

  
  ci:
    runs-on: ubuntu-20.04
    needs: [ build, lint, test, verification]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"        
