name: Build

on:
  push:
    branches:
      - master
    tags: [ "*" ]
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: sbt compile

      - name: Check Style
        run: sbt check
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Test
        run: sbt test
  
  #      - name: Run Test
  #        if: success() || failure()
  #        run: sbt coverage test
  #
  #      - name: Aggregate coverage report
  #        run: sbt coverageAggregate
  #
  #      - name: Upload test coverage report
  #        run: bash <(curl -s https://codecov.io/bash)
  
  verification:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Check Binary Compatibility
        run: sbt runPluginVerifier

  
  ci:
    runs-on: ubuntu-20.04
    needs: [ build, test, verification]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"        
